# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 
 
Name:       sphinxbase
 
# >> macros
# << macros
 
Summary:    Common library for sphinx speech recognition.
Version:    0.8
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://cmusphinx.sourceforge.net/
Source0:    http://ufpr.dl.sourceforge.net/project/cmusphinx/%{name}/%{version}/%{name}-%{version}.tar.gz
Source100:  sphinxbase.yaml
Requires:   bison
BuildRequires:  libtool
 
%description
Common library for sphinx speech recognition.
 
 
%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
 
%description devel
Development files for %{name}.
 
%prep
%setup -q -n %{name}-%{version}
 
# >> setup
# << setup
 
%build
# >> build pre
# << build pre
 
%autogen --disable-static
%configure --disable-static \
    --enable-fixed \
    --prefix=/usr/
 
make %{?_smp_mflags}
 
# >> build post
# << build post
 
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
 
# >> install post
# << install post
 
%files
%defattr(-,root,root,-)
%{_libdir}/libsphinx*
%{_bindir}/sphinx*
# >> files
# << files
 
%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/pkgconfig/sphinxbase.pc
%{_includedir}/%{name}
# << files devel
