# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sphinxbase

# >> macros
# << macros

Summary:    Common library for sphinx speech recognition.
Version:    0.8
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://cmusphinx.sourceforge.net/
Source0:    http://ufpr.dl.sourceforge.net/project/cmusphinx/%{name}/%{version}/%{name}-%{version}.tar.gz
Source100:  sphinxbase.yaml
Requires:   bison
BuildRequires:  libtool
BuildRequires:  bison

%description
Common library for sphinx speech recognition.


%package python2
Summary:    Python2 support for pocketsphinx
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   %{name}-python2

%description python2
This package provides python 2.7 bindings
for the speech recognition libary sphinx


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%autogen --disable-static
%configure --disable-static \
    --enable-fixed \
    --prefix=/usr/

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/libsphinx*
%{_bindir}/sphinx*
# >> files
# << files

%files python2
%defattr(-,root,root,-)
%{_libdir}/python2.7/site-packages/SphinxBase-0.8-py2.7.egg-info/PKG-INFO
%{_libdir}/python2.7/site-packages/SphinxBase-0.8-py2.7.egg-info/SOURCES.txt
%{_libdir}/python2.7/site-packages/SphinxBase-0.8-py2.7.egg-info/dependency_links.txt
%{_libdir}/python2.7/site-packages/SphinxBase-0.8-py2.7.egg-info/top_level.txt
%{_libdir}/python2.7/site-packages/sphinxbase.so
# >> files python2
# << files python2

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/pkgconfig/sphinxbase.pc
%{_includedir}/%{name}
# << files devel
